var buttonColours = ["red","blue","green","yellow"];        //all the available buttons
var gamePattern = [];                   //pattern generated by the game
var userClickedPattern = [];            //pattern clicked by the player
var started = 0;                        //flag to check if the game has been started
var level = 0;                          //level indicator


$(document).keypress(function(){            //this detects for any keypresses and starts the game
    $("#level-title").text("Level "+level); //changes the h1 to display current level
    if(started === 0){                      //prevents unintentional restarting the game by keystrokes
        nextSequence();                     //starts the game
        started = 1;
    }
});

function animatePress(currentColour) {      //animates button click
    $("#"+currentColour).addClass("pressed");
    setTimeout(function(){
        $("#"+currentColour).removeClass("pressed");
    },100);
}

function playSound(name) {                  //plays button sound
    var audio = new Audio("sounds/"+name+".mp3");
    audio.play();
}

$(".btn").on("click",function (event) {     //detects the user clicked button
    userChosenColour = event.target.id;
    userClickedPattern.push(userChosenColour);  //adds the user clicked pattern
    playSound(userChosenColour);
    animatePress(userChosenColour);
    checkAnswer((userClickedPattern.length)-1); //compares the user input value with the game generated pattern value of the same index
});

function nextSequence(){                    //starts the game or takes it to new level
    level = level + 1;
    $("#level-title").text("Level "+level);                                     //changing the level every time game is initiated
    var randomNumber = Math.floor(Math.random()*4);                             //choosing random number from 0 to 3
    var randomChosenColour = buttonColours[randomNumber];                       //choosing a random colour from the four colours
    gamePattern.push(randomChosenColour);                                       //pushing the game pattern into our array
    $("#"+randomChosenColour).fadeIn(100).fadeOut(100).fadeIn(100);             //animating the buttons
    playSound(randomChosenColour);
}


//game logic


function checkAnswer(currentLevel){
    if(userClickedPattern[currentLevel] === gamePattern[currentLevel]){         //checks the last entered input with the game generated pattern of same index 
        // console.log("success");
        if(userClickedPattern.length === gamePattern.length){                   //if user has entered the pattern correctly and reached the end of current level
            setTimeout(nextSequence,1000);              //wait for 1 second and then start the next level
            userClickedPattern=[];                      //clear the user input so that the user has to enter the full pattern from the start
        }
    }
    else{                                                                       //the user entered wrong input from the game pattern
        // console.log("wrong");
        playSound("wrong");
        $(document.body).addClass("game-over");         //wrong answer animations and sounds
        setTimeout(function(){
            $(document.body).removeClass("game-over");
        },200)
        $("#level-title").text("Game-Over. Press Any Key To Restart.")
        startOver();            //restart
    }
}

function startOver(){           //restarts the game
    gamePattern=[];
    userClickedPattern=[];
    started = 0;
    level = 0;
    // $("#level-title").text("Press A Key to Start.");
}

